### ISSUE TITLE
Error running webServer.py

### ISSUE THREAD

**Issue by nin9creative** [adeept/adeept_alter#1]
My son and I went through the process of building the alter "dog" model following the instructions.

After pulling down the repo and running setup.py, we are running into this error when trying to run the webServer.py and get the robot up and running.

pi@raspberrypi:~/adeept_alter/server $ sudo python3 webServer.py

Traceback (most recent call last):

  File "webServer.py", line 135, in <module>

    flask_app = app.webapp()

AttributeError: module 'app' has no attribute 'webapp'

**Comment by nin9creative** [comment]
I saw someone posted an update on some files to resolve the above - but now there is another error.


Ok, well that got a little farther – but still an error.

There seems to be something wrong with your setup / install script that is causing this issue.

Also I read something that Adafruit_BBIO.GPIO is deprecated and that a different library should be used???
https://github.com/adafruit/Adafruit_Python_GPIO


pi@raspberrypi:~ $ sudo python3 adeept_alter/server/webServer.py
Traceback (most recent call last):
  File "adeept_alter/server/webServer.py", line 19, in <module>
    import app
  File "/home/pi/adeept_alter/server/app.py", line 8, in <module>
    from camera_opencv import Camera
  File "/home/pi/adeept_alter/server/camera_opencv.py", line 6, in <module>
    import alterMove
  File "/home/pi/adeept_alter/server/alterMove.py", line 7, in <module>
    import oledCtrl
  File "/home/pi/adeept_alter/server/oledCtrl.py", line 22, in <module>
    disp = Adafruit_SSD1306.SSD1306_128_64(rst=RST)
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 243, in __init__
    gpio, spi, i2c_bus, i2c_address, i2c)
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_SSD1306/SSD1306.py", line 85, in __init__
    self._gpio = GPIO.get_platform_gpio()
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_GPIO/GPIO.py", line 420, in get_platform_gpio
    import Adafruit_BBIO.GPIO
ModuleNotFoundError: No module named 'Adafruit_BBIO'

**Comment by anonymousm3** [comment]
I am having issues running the webServer.py manually
Also in the startup.sh, it calls the python script server.py under server directory and not the webServer.py

**Comment by adeept** [comment]
Hello,
Both server.py and webServer.py programs need to occupy the camera. If you want to manually run the program related to the camera, you need to close the automatic running program.
Best!


Technical Support
***@***.***


签名由 网易邮箱大师 定制


On 4/25/2021 ***@***.***> wrote：


I am having issues running the webServer.py manually
 Also in the startup.ssh, it calls the python script server.py under server directory and not the webServer.py

**Comment by anonymousm3** [comment]
> Hello, Both server.py and webServer.py programs need to occupy the camera. If you want to manually run the program related to the camera, you need to close the automatic running program. Best! Technical Support ***@***.*** 签名由 网易邮箱大师 定制 On 4/25/2021 ***@***.***> wrote： I am having issues running the webServer.py manually Also in the startup.ssh, it calls the python script server.py under server directory and not the webServer.py — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

How can we edit the web interface, I want to add functions, I bought another LED that supports RGB functions and I wanna add a function to the web control interface

**Comment by adeept** [comment]
Hello,


The WEB control interface is written through the vue.js framework. The program is encapsulated in the adeept_alter/server/dist file.
If you want to modify this web interface, you can modify it through the following source files.
Source file download address:  https://www.adrive.com/public/E8Fxpy/adeept_bot_controller_web.rar



Best!


Technical Support
***@***.***


签名由 网易邮箱大师 定制


On 4/26/2021 ***@***.***> wrote：


Hello, Both server.py and webServer.py programs need to occupy the camera. If you want to manually run the program related to the camera, you need to close the automatic running program. Best! Technical Support @.*** 签名由 网易邮箱大师 定制 On 4/25/2021 @.***> wrote： I am having issues running the webServer.py manually Also in the startup.ssh, it calls the python script server.py under server directory and not the webServer.py — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
How can we edit the web interface, I want to add functions, I bought another LED that supports RGB functions and I wanna add a function to the web control interface

**Comment by anonymousm3** [comment]
> Hello, The WEB control interface is written through the vue.js framework. The program is encapsulated in the adeept_alter/server/dist file. If you want to modify this web interface, you can modify it through the following source files. Source file download address: https://www.adrive.com/public/E8Fxpy/adeept_bot_controller_web.rar Best! Technical Support ***@***.*** 签名由 网易邮箱大师 定制 On 4/26/2021 ***@***.***> wrote： Hello, Both server.py and webServer.py programs need to occupy the camera. If you want to manually run the program related to the camera, you need to close the automatic running program. Best! Technical Support @.*** 签名由 网易邮箱大师 定制 On 4/25/2021 @.***> wrote： I am having issues running the webServer.py manually Also in the startup.ssh, it calls the python script server.py under server directory and not the webServer.py — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. How can we edit the web interface, I want to add functions, I bought another LED that supports RGB functions and I wanna add a function to the web control interface — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for this information, so this must be very hard and tricky to edit the web interface. This will be hard for me.
